---
title: "BMEG 310 Assignment 2"
author: "Group 14: Wesley Chan, Flora Deng, Mary Graves"
date: "2022-10-17"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
# libraries
library(ggplot2)
library(ROCR)
```

```{r}
# loading in data
ovarian.dataset <- read.delim("ovarian.data", sep=",", header = FALSE)
features <- c("perimeter", "area", "smoothness", "symmetry", "concavity",
paste("protein", seq(1, 25) ))
names(ovarian.dataset) <- c("cell_id", "diagnosis", features)

# check data (REMOVE FOR SUBMISSION)
head(ovarian.dataset)
```

```{r}
# Question 1 - Dimensionality Reduction


```
```{r}
#Question 1.1
ovarian.pca <- prcomp(ovarian.dataset[,c(3:32)], center = TRUE,scale. = TRUE)

summary(ovarian.pca)

# According to the proportion of variance in summary, 44.3% variation is associated with PC1.
```

```{r}
# Question 1.2
screeplot(ovarian.pca, type = "l", npcs = 30, main = "Screeplot of the 30 PCs")
abline(h = 1, col="red")
legend("topright", legend=c("Eigenvalue = 1"),
       col=c("red"))

cumpro <- cumsum(ovarian.pca$sdev^2 / sum(ovarian.pca$sdev^2))
plot(cumpro[0:30], xlab = "PC #", ylab = "Amount of explained variance", main = "Cumulative variance plot")
abline(v = 6, col="blue")
abline(h = 0.88759, col="blue")
legend("topleft", legend=c("Cut-off @ PC6"),
       col=c("blue"))

# Based on cumulative proportion we get in Q1.1 and plots we get, we can see that the first 6 components (PC1-PC7) has an eigenvalue > 1 and represent 90% of the variance in the data. We can preserve 90% of the variability by 6 dimensionality of the reduced feature space.
```

```{r}
# Question 1.3
library(devtools)

remotes::install_github("vqv/ggbiplot")

library(ggbiplot)

ggbiplot(ovarian.pca, labels=ovarian.dataset$diagnosis ,groups = ovarian.dataset$diagnosis)
```

```{r}
# Question 1.4
ggplot(data = ovarian.dataset, mapping = aes(x = area, y = concavity,color = as.factor(diagnosis))) + geom_point()
```

```{r}
# Question 1.5
# I think the first figure is better because the distribution of points in Figure 1 is more dense and there is not much overlap
```

```{r}
# Question 1.6
# Separate
for(i in 1:30){
  boxplot(ovarian.pca$x[,i])
}
# Total
boxplot(ovarian.pca$x)
```

```{r}
# Question 2 - Clustering
```

```{r}
# Question 3 - Classification

# Divide data into training set and test set
ovarian.dataset.train <- ovarian.dataset[sample(nrow(ovarian.dataset))
  [1:(nrow(ovarian.dataset)/2)],]
ovarian.dataset.test <- ovarian.dataset[sample(nrow(ovarian.dataset))
  [(nrow(ovarian.dataset)/2):(nrow(ovarian.dataset))],]
```

```{r}
# Question 3.1
glm.fit <- glm(as.factor(diagnosis) ~., data = ovarian.dataset.train[,c(3:32)], family = binomial)

summary(glm.fit)
```

```{r}
glm.probs <- predict(glm.fit,ovarian.dataset.test[,c(3:32)],type = "response")

glm.probs[1:5]
```

```{r}
glm.pred <- ifelse(glm.probs > 0.5, "M", "B")
head(ovarian.dataset.test)
table(glm.pred,ovarian.dataset.test$diagnosis)
mean(glm.pred == ovarian.dataset.test$diagnosis)
```

```{r}
# Question 3.2
ovarian.pca5 <- ovarian.pca$x[,1:5]
ovarian.dataset.train.pc5 <- ovarian.pca5[sample(nrow(ovarian.pca5))[1:(nrow(ovarian.pca5)/2)],]
ovarian.dataset.test.pc5 <- ovarian.pca5[sample(nrow(ovarian.pca5))[(nrow(ovarian.pca5)/2):(nrow(ovarian.pca5))],]

glm.fit.pc5 <- glm(as.factor(diagnosis) ~., data = as.data.frame(ovarian.dataset.train.pc5), family = binomial)

summary(glm.fit.pc5)
```

```{r}
glm.probs.pc5 <- predict(glm.fit.pc5,as.data.frame(ovarian.dataset.test.pc5),type = "response")

glm.probs.pc5[1:5]
```

```{r}
glm.pred.pc5 <- ifelse(glm.probs.pc5 > 0.5, "M", "B")
head(as.data.frame(ovarian.dataset.test.pc5))
table(glm.pred.pc5,ovarian.dataset.test$diagnosis)
mean(glm.pred.pc5 == ovarian.dataset.test$diagnosis)
```

```{r}
# Question 3.5
library(ROCR)
pred.prob <- predict(glm.fit, ovarian.dataset, type="response")
predict <- prediction(pred.prob, ovarian.dataset$diagnosis, label.ordering=c("B","M"))
perform <- performance(predict,"tpr","fpr")
plot(perform,colorize=TRUE)
```

```{r}
# Contribution Statement 

# Wesley Chan (75520023): did literally nothing
# Flora Deng (): 
# Mary Graves (): 
```

